[#12][ADD] 환경별 DB properties 셋팅
bom-bom-study/meeting-room-reservation pull request #17
Opened 2019-06-04 02:31 UTC by korea8378

resolve #12 #11

2019-06-04 02:33 UTC, korea8378 commented
- JPA 프로퍼티 설정 : https://zetawiki.com/wiki/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8_JPA_%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0
- H2 Intellij Console 사용법 : https://jojoldu.tistory.com/234
- H2 서버모드 버전 이슈 : https://github.com/h2database/h2database/issues/1901

2019-06-05 09:28 UTC, jo-bata requested changes
@korea8378 
- 덕분에 환경설정 공부가 되었어요 감사합니다 ! ㅎㅎ
- 추가 건의사항으로 설정파일을 YAML으로 작성해보는건 어떨까요?

2019-06-05 09:28 UTC, jo-bata commented on build.gradle
> +apply plugin: 'eclipse'
- IntelliJ를 사용하는데 eclipse는 빼도되지 않을까요??

2019-06-05 09:28 UTC, jo-bata commented on build.gradle
> +    implementation 'org.projectlombok:lombok'
- lombok은 compileonly로 바꾸는 것이 좋을 것 같아요!

2019-06-05 09:28 UTC, jo-bata commented on src/main/resources/application-local.properties
> +spring.datasource.platㅇform=h2
- platform 오타 수정해야할 것 같습니다!

2019-06-05 11:02 UTC, korea8378 commented
@jo-bata review 감사합니다. 업데이트 후 push 했습니다~~~

2019-06-05 11:13 UTC, jo-bata approved these changes
@korea8378 
- 확인했습니다. 고생하셨습니다 ! ㅎㅎ

2019-06-05 11:14 UTC, merged